---
title: "git_01"
author: "Anthony Monroy"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves
      Did gyre and gimble in the wabe:
All mimsy were the borogoves,
      And the mome raths outgrabe.
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Some say the world will end in fire,
Some say in ice.
From what I’ve tasted of desire
I hold with those who favor fire.
But if it had to perish twice,
I think I know enough of hate
To say that for destruction ice
Is also great
And would suffice.
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,
      Shining with all his might:
He did his very best to make
      The billows smooth and bright —
And this was odd, because it was
      The middle of the night.

The moon was shining sulkily,
      Because she thought the sun
Had got no business to be there
      After the day was done —
"It's very rude of him," she said,
      "To come and spoil the fun."
## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
He grew up old school times have changed. When he was young they told him date your own race but he was his own person. He wasn't into the cholo life he grew his hair and educated himself. Times have changed back in the days you worked at it to be in a relationship. Now a days women give it away being promiscuous expecting respect or like it with be more than just a one night stand. He never said I love you unless he meant it and observed her actions how can a person say I love you but be all up on another person. Most people play the game but and up getting played. being the fool because all their shady acts catch up to them blow up in their face. Times have changed from child to adult what was cool is no more or what was a hit is now a classic. Things come and go in the blink of an eye another trend to replace the old one.